"""Add agent_politeness_score

Revision ID: 14475fc6aedc
Revises: b18378c5e7f3
Create Date: 2026-06-04 11:38:31.160492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14475fc6aedc'
down_revision: Union[str, Sequence[str], None] = 'b18378c5e7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callerrecord', sa.Column('agent_politeness_score', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('callerrecord', 'agent_politeness_score')
    # ### end Alembic commands ###
