"""Add metadata to CallerRecord

Revision ID: b18378c5e7f3
Revises: ce291f9975a8
Create Date: 2026-06-03 15:50:16.279468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18378c5e7f3'
down_revision: Union[str, Sequence[str], None] = 'ce291f9975a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callerrecord', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('callerrecord', sa.Column('department', sa.String(), nullable=True))
    op.add_column('callerrecord', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('callerrecord', 'created_at')
    op.drop_column('callerrecord', 'department')
    op.drop_column('callerrecord', 'agent_id')
    # ### end Alembic commands ###
