"""Create performance analytics table

Revision ID: bc4b90f392e2
Revises: 14475fc6aedc
Create Date: 2026-06-04 15:43:44.366610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4b90f392e2'
down_revision: Union[str, Sequence[str], None] = '14475fc6aedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performanceanalyticsrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=False),
    sa.Column('processing_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performanceanalyticsrecord')
    # ### end Alembic commands ###
