"""Update caller record

Revision ID: ce291f9975a8
Revises: fbb462f5934a
Create Date: 2026-06-03 14:06:08.913296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce291f9975a8'
down_revision: Union[str, Sequence[str], None] = 'fbb462f5934a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callerrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('callerrecord')
    # ### end Alembic commands ###
